### ISSUE TITLE
[Test] json syntax error not caught? 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10029]
https://ci.cdnjs.com/cdnjs/cdnjs/1281
```
undefined:42
  "license": "MIT"
  ^
SyntaxError: Unexpected string
    at Object.parse (native)
    at /drone/src/github.com/cdnjs/cdnjs/tools/createSparseCheckoutConfigForCI.js:21:22
    at /drone/src/github.com/cdnjs/cdnjs/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/drone/src/github.com/cdnjs/cdnjs/node_modules/async/dist/async.js:941:9)
    at eachOf (/drone/src/github.com/cdnjs/cdnjs/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/drone/src/github.com/cdnjs/cdnjs/node_modules/async/dist/async.js:3089:3)
    at Object.<anonymous> (/drone/src/github.com/cdnjs/cdnjs/tools/createSparseCheckoutConfigForCI.js:20:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
```

This error should be caught here but didn't:
https://github.com/cdnjs/cdnjs/blob/master/test/valid-packages-test.js#L11-L28
```js
function parse(jsonFile, ignoreMissing) {
  var content;

  try {
    content = fs.readFileSync(jsonFile, 'utf8');
  } catch (err1) {
    if (!ignoreMissing) {
      assert.ok(0, jsonFile + " doesn't exist!");
    }
    return null;
  }
  try {
    return JSON.parse(content);
  } catch (err2) {
    assert.ok(0, jsonFile + " failed to parse, you can validate your json here: http://jsonlint.com/");
    return null;
  }
}
```

Should take a look at it ...

**Comment by PeterDaveHello** [comment]
@pvnr0082t would you like to take this?

**Comment by pvnr0082t** [comment]
@PeterDaveHello Okay, I'll try it.

**Comment by petrgazarov** [comment]
Interesting... I replicated the package json without the comma before the license... `npm test` caught it for me locally.

**Comment by sashberd** [comment]
@PeterDaveHello Is this one already fixed?

**Comment by PeterDaveHello** [comment]
@sashberd not fully but almost, until the next version of nodejs docker image which is based on the new alpine linux.

**Comment by PeterDaveHello** [comment]
should be fixed now, as it's before the package.json validation, use jsonlint to detect it.
