### ISSUE TITLE
[Request] Add angular2-materialize

### ISSUE THREAD

**Issue by yilmazay74** [cdnjs/cdnjs#11311]
**Library name:** angular2-materialize
**Git repository url:** https://github.com/InfomediaLtd/angular2-materialize
**npm package name or url** (if there is one):  https://www.npmjs.com/package/angular2-materialize
**License (List them all if it's multiple):** MIT
**Official homepage:** http://materializecss.com/

Could you please provide an on the fly access url for angular2-materialize to be used in angular 2 compnents?
I searched it on unpkg.com but it doesn't have it either.
I think angular 2 materialize is one of the most wanted ui package.
So I hope you  accept my request.
Regards
something like https://cdnjs.com/angular2-materialize

**Comment by sufuf3** [comment]
@yilmazay74 Do you mean the library you want to add is  as the followings link?
https://www.npmjs.com/package/angular2-materialize
https://github.com/InfomediaLtd/angular2-materialize

**Comment by yilmazay74** [comment]
No. That one is an html page that describes materialize. What I want is a url of the materialize js, which I will include in my system.config.js of my angulaar 2 project. 
It will be the doing the same job as "npm install angular2-materialize --save". 
Instead of downloading angular2-materialize package in node_moduels, I want it to be accessible from a url. 
something like this:
  <script src="https://npmcdn.com/reflect-metadata@0.1.3"></script>

Regards

**Comment by sufuf3** [comment]
Is this Library - [angular2-materialize](https://www.npmjs.com/package/angular2-materialize) you want us to host?
Sorry for my ambiguous comment.

**Comment by yilmazay74** [comment]
yes, that one.

Thanks

**Comment by yilmazay74** [comment]
By the way, Could you please host also primeng package?
the one that is installed via "npm install -g primeng".

Should I create a new request for primeng?

regards

**Comment by sufuf3** [comment]
Yes. Please create a new issue for primeng.
And please provide us the details of this primeng lib, thanks.

**Comment by yilmazay74** [comment]
By the way, could you please let us know, approximately when angular2-materialize will be available on cdnjs ?

**Comment by sufuf3** [comment]
We will work on it as soon as possible, but I can't answer you when the library will be available on CDNJS.
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@sufuf3 you should update the first comment for library info ...

**Comment by sufuf3** [comment]
Sorry, I updated it.

**Comment by dakshshah96** [comment]
@PeterDaveHello @sufuf3 Please check https://unpkg.com/angular2-materialize@15.0.4/dist/

I doubt these can be used directly in the browser. Awaiting your response.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 please help confirm with its author.

**Comment by yilmazay74** [comment]
Hi, 
We are testing it. I will let you know very soon.

Thanks a lot.

**Comment by PeterDaveHello** [comment]
@yilmazay74 thanks!

**Comment by yilmazay74** [comment]
Hi,
When I add materialize package to my app.module.ts, I am getting the following error message 

(index):58 Error: TypeError: ctorParameters.map is not a function
	    at ReflectionCapabilities.parameters (https://npmcdn.com/@angular/core@2.0.0-rc.5//bundles/core.umd.js:5006:51)
	    at Reflector.parameters (https://npmcdn.com/@angular/core@2.0.0-rc.5//bundles/core.umd.js:5191:52)
	    at CompileMetadataResolver.getDependenciesMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13459:83)
	    at CompileMetadataResolver.getTypeMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13424:30)
	    at CompileMetadataResolver.getDirectiveMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13176:32)
	    at eval (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13243:53)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13236:48)
	    at eval (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13228:58)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13215:48)
	    at RuntimeCompiler._compileComponents (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:15845:51)
	    at RuntimeCompiler._compileModuleAndComponents (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:15769:41)
	    at RuntimeCompiler.compileModuleAsync (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:15746:25)
	    at PlatformRef_._bootstrapModuleWithZone (https://npmcdn.com/@angular/core@2.0.0-rc.5//bundles/core.umd.js:9991:29)
	Error loading http://localhost:8080/app/main.ts

**Comment by yilmazay74** [comment]
At first it seems that it has nothing to do with angular2 materialize, however, it does.
When I remove     
import { MaterializeModule } from "angular2-materialize"; from my app.module.ts 
it works without problems (but without materialize of course).

Note: I am dynamically installing angular2materialize in my system.config.js as below:
'angular2-materialize': 	  'https://unpkg.com/angular2-materialize@15.0.4/dist/materialize-module.js'

Any suggestions about what could be wrong ?
Regards

**Comment by yilmazay74** [comment]
By the way:
I am also importing materialize module in NgModule section as below: 

@NgModule({
  imports:      [ BrowserModule, HttpModule, FormsModule, RouterModule, AppRoutingModule, MaterializeModule],

**Comment by yilmazay74** [comment]
If I change 
    'angular2-materialize': 'https://unpkg.com/angular2-materialize@15.0.4/dist/materialize-module.js' 
 as
    'angular2-materialize': 	  'https://unpkg.com/angular2-materialize@15.0.4/dist/index.js',
then it  says it cannot find materialize css.
Perhaps, there is a dependency issue her, it can not find materialize css files that angular2-materialize is depending on. 
(index):58 Error: Error: Couldn't find Materialize object on window. It is created by the materialize-css library. Please import materialize-css before importing angular2-materialize.
	    at execute (https://unpkg.com/angular2-materialize@15.0.4/dist/index.js!transpiled:30:23) [<root>]
	Error loading http://localhost:8080/app/main.ts

**Comment by PeterDaveHello** [comment]
I'm not sure if this is this angular2-materialize problem you mention above is something we can deal with, maybe open an issue to its repo/author first?
