### ISSUE TITLE
1-2 minute intermittency - syntax error - https://cdnjs.cloudflare.com/ajax/libs/what-input/4.0.4/what-input.min.js

### ISSUE THREAD

**Issue by NicolaSA** [cdnjs/cdnjs#14015]
Hi Folks,

Our client's website has started loading slow and yesterday and day before logs were clear.
Today 10:30 uk time the logs are complaining about syntax errors, can anyone advise if maintenance or changes could have affected: https://cdnjs.cloudflare.com/ajax/libs/what-input/4.0.4/what-input.min.js

It's happening on varying urls too, probably due to the common top right  search form on every page.
Any advice appreciated please,
Nix

An unhandled exception occurred
WebMarkupMin.Core.MarkupMinificationException: Category: HTML_PARSING_ERROR
Message: In the start tag <input> found invalid characters.

Line 561: …om/ajax/libs/what-input/4.0.4/what-input.min.js" type="text/javascript"></script><script src=…

   at WebMarkupMin.Core.Loggers.ThrowExceptionLogger.Error(String category, String message, String filePath, Int32 lineNumber, Int32 columnNumber, String sourceFragment)
   at WebMarkupMin.Core.GenericHtmlMinifier.Minify(String content, String fileContext, Encoding encoding, Boolean generateStatistics)
   at WebMarkupMin.AspNet4.Common.MarkupMinificationFilterStream.Close()
   at ClientDependency.Core.Module.ResponseFilterStream.Close() in \ClientDependency\ClientDependency\src\ClientDependency.Core\Module\ResponseFilterStream.cs:line 313
   at System.Web.HttpWriter.FilterIntegrated(Boolean finalFiltering, IIS7WorkerRequest wr)
   at System.Web.HttpResponse.FilterOutput()
   at System.Web.HttpApplication.CallFilterExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by xtuc** [comment]
Do you know from which location that error occurred? are you using a proxy before reaching cdnjs.cloudflare.com?

**Comment by nvisage-gf** [comment]
Apologies this was not a cdnjs issue, please close.

Application exception was generated by unencoded user generated content that could not be parsed; our stack trace was a little unhelpful :(
